version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  db:
    image: postgres
    environment:
      POSTGRES_DB: moneynote
      POSTGRES_USER: postgres
    ports:
      - '5433:5432'
    expose:
      - '5433'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
