version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # 로컬 DB와 연결할 때에는 localhost가 아니라 아래와 같이 .env 파일과 통일시켜야한다.
      POSTGRES_HOST: db-moneynote.chcibpobmzks.ap-northeast-2.rds.amazonaws.com
      POSTGRES_PORT: 5432
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
