export const IAUTH_SERVICE = 'IAuthService'
export const IBUDGET_SERVICE = 'IBudgetService'
export const IEXPENSE_SERVICE = 'IExpenseService'
export const IUSER_SERVICE = 'IUserService'
export const ICACHE_SERVICE = 'ICacheService'
export const IEXPENSE_CALCULATION_SERVICE = 'IExpenseCalculationService'
export const IEXPENSE_MESSAGE_SERVICE = 'IExpenseMessageService'
export const IBUDGET_DESIGN_STRAGTEGY = 'IBudgetDesignStrategy'

export const CONFIG_OPTIONS = 'CONFIG_OPTIONS'
