export const IAUTH_SERVICE = Symbol('IAuthService')
export const IBUDGET_SERVICE = Symbol('IBudgetService')
export const IEXPENSE_SERVICE = Symbol('IExpenseService')
export const IUSER_SERVICE = Symbol('IUserService')
export const ICACHE_SERVICE = Symbol('ICacheService')
export const IEXPENSE_CALCULATION_SERVICE = Symbol('IExpenseCalculationService')
export const IEXPENSE_MESSAGE_SERVICE = Symbol('IExpenseMessageService')
export const IBUDGET_DESIGN_STRAGTEGY = Symbol('IBudgetDesignStrategy')

export const CONFIG_OPTIONS = Symbol('CONFIG_OPTIONS')
