name: CI/CD Docker

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [main]

# 환경설정
env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
  VERSION: ${{ github.sha }}
  IMAGE_NAME: moneynote
  CONTAINER_NAME: moneynote-server

jobs:
  # 빌드 Job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # aws에 로그인 후 ECR에 푸시
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login too Amazon ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest ${{ env.ECR_REGISTRY }}/$IMAGE_NAME:latest
          docker push ${{ env.ECR_REGISTRY }}/$IMAGE_NAME:latest

  # 배포 Job
  deploy:
    needs: build # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [self-hosted, moneynote] # AWS ./configure에서 사용할 label명
    steps:
      # 3000 -> 80 포트로 수행하도록 지정
      - name: Pull image and run
        run: |
          docker pull ${{ env.ECR_REGISTRY }}/$IMAGE_NAME:latest
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          docker rmi ${{ env.ECR_REGISTRY }}/$IMAGE_NAME:latest || true
          docker run -d -p 80:3000 --name ${{ env.CONTAINER_NAME }} --restart always ${{ env.ECR_REGISTRY }}/$IMAGE_NAME:latest
